// src/routes/writing/chinese-restaurant/+page.svelte
<script lang="ts">
	import back_button from "$lib/imgs/back.png";
</script>
<svelte:head>
	<title>כמה שירים (Some Poems) | Henry Wandover</title>
	<meta name="title" content="Henry Wandover's Writing" />
	<meta
		name="description"
		content="A personal site made by Henry Wandover, for Henry Wandover"
		/>
	<meta name="keywords" content="Computer Science, Writing, Blog" />
	<meta name="author" content="Henry Wandover" />
</svelte:head>

<div class="content">
    <a href="/"><img src={back_button} /></a>
		<h2>Chinese Restaurant</h2>
		<br>

		<p>
		Tears in a Chinese restaurant,<br>
		Sodium droplets mixing with MSG.<br>
		The chemical reaction in her head, is<br>
		Much more interesting than<br>
		The watercolor appearing on her plate.<br>
		What man? Or woman?<br>
		What cliche?<br>
		While dull, still<br>
		Can cut and mange the foolhardy.
		</p>
		
</div>

// app/routes/writing/chinese-restaurant.tsx
import Back from "../../mods/back";
import type { Route } from "../writing/+types/chinese-restaurant";

export function meta({}: Route.MetaArgs) {
  return [
	{ title: "Chinese Restaurant | Henry Wandover" },
	{ name: "description", content: "A personal site made by Henry Wandover, for Henry Wandover" },
	{ name: "keywords", content: "Computer Science, Writing, Blog" },
	{ name: "author", content: "Henry Wandover" },
  ];
}

export default function ChineseRestuarant() {
  return (
	<div className="content">
		<Back />

		<h2>Chinese Restaurant</h2>
		<br />

		<p>
		Tears in a Chinese restaurant,<br />
		Sodium droplets mixing with MSG.<br />
		The chemical reaction in her head, is<br />
		Much more interesting than<br />
		The watercolor appearing on her plate.<br />
		What man? Or woman?<br />
		What cliche?<br />
		While dull, still<br />
		Can cut and mange the foolhardy.
		</p>
			
	</div>
  );
}
