// src/lib/modules/projects.svelte
<h2>Projects</h2>

<ul>
	<li>
		<a href="https://github.com/yung-turabian/libreis/">libreis</a>
		<br />
		<small
			>A general-purpose C/C++ library; <a
				href="https://yung-turabian.github.io/reislib/"
				title="View Doxygen pages for my lib">docs here</a
			></small
		>
	</li>
	<li>
		<a
			href="https://github.com/yung-turabian/hasqtan/"
			target="_blank"
			rel="noreferrer noopener"
			title="Git repository">Hasqtan</a
		>
		<br />
		<small>Toy functional language</small>
	</li>
	<li>
		<a
			href="https://yung-turabian.itch.io/turbulenttrader"
			target="_blank"
			rel="noreferrer noopener"
			title="Game">Turbulent Trader</a
		>
		<br />
		<small>Game jam game about bargaining</small>
	</li>
	<li>
		<a
			href="https://github.com/yung-turabian/zephyr"
			target="_blank"
			rel="noreferrer noopener"
			title="Links Tools">zephyr</a
		>
		<br />
		<small
			>Live reloading for <a
				href="https://www.links-lang.org"
				target="_blank"
				rel="noreferrer noopener"
				title="Links homepage">Links</a
			></small
		>
	</li>
	<li>
		<a
			href="/links-lang"
			title="Deamon">Subkind Classes for Links</a
		>
		<br />
		<small>My senior project at Bard College</small>
	</li>
	<li>
		<a
			href="https://github.com/yung-turabian/porter"
			target="_blank"
			rel="noreferrer noopener"
			title="Daemon">porter</a
		>
		<br />
		<small>A daemon for an organized filesystem</small>
	</li>
</ul>

// app/home_page_modules/projects.tsx
export function Projects() {
    return (
        <div id="about">
            <h2>Projects</h2>

            <ul>
                <li>
                    <a href="https://github.com/yung-turabian/libreis/">
                        libreis
                    </a>
                    <br />
                    <small>
                        A general-purpose C/C++ library;{" "}
                        <a
                            href="https://yung-turabian.github.io/reislib/"
                            title="View Doxygen pages for my lib"
                        >
                            docs here
                        </a>
                    </small>
                </li>
                <li>
                    <a
                        href="/hasqtan"
                        target="_blank"
                        rel="noreferrer noopener"
                        title="Git repository"
                    >
                        Hasqtan
                    </a>
                    <br />
                    <small>Toy functional language</small>
                </li>
                <li>
                    <a
                        href="https://yung-turabian.itch.io/turbulenttrader"
                        target="_blank"
                        rel="noreferrer noopener"
                        title="Game"
                    >
                        Turbulent Trader
                    </a>
                    <br />
                    <small>Game jam game about bargaining</small>
                </li>
                <li>
                    <a
                        href="https://github.com/yung-turabian/zephyr"
                        target="_blank"
                        rel="noreferrer noopener"
                        title="Links Tools"
                    >
                        zephyr
                    </a>
                    <br />
                    <small>
                        Live reloading for{" "}
                        <a
                            href="https://www.links-lang.org"
                            target="_blank"
                            rel="noreferrer noopener"
                            title="Links homepage"
                        >
                            Links
                        </a>
                    </small>
                </li>
                <li>
                    <a href="/my-work-on-links" title="Links">
                        Subkind Classes for Links
                    </a>
                    <br />
                    <small>My senior project at Bard College</small>
                </li>
                <li>
                    <a
                        href="https://github.com/yung-turabian/porter"
                        target="_blank"
                        rel="noreferrer noopener"
                        title="Daemon"
                    >
                        porter
                    </a>
                    <br />
                    <small>A daemon for an organized filesystem</small>
                </li>
            </ul>
        </div>
    );
}
