// app/home_page_modules/about.tsx
import Resume from "/documents/Resume.pdf";

export function About() {
    return (
        <div id="projects">
            <h2>About Me</h2>
            <p>
                Hey there, welcome to my site! I'm Henry, a recent graduate of
                Bard College with a degree in Computer Science and Politics.
                Currently residing in Philadelphia, I work on software projects
                related to programming languages and desktop developer tools.
                Along with what I do in my free time, I am also looking for
                work, ideally, either in backend software or game development.
                If you have an opportunity, or know of one, feel free to check
                out my{" "}
                <a
                    href={Resume}
                    hrefLang="en"
                    target="_blank"
                    rel="noreferrer noopener"
                    type="application/pdf"
                >
                    résumé
                </a>
                , as well as the rest of my site.
            </p>
            <p>
                The ideal way of getting in contact is by email:{" "}
                <b>henrywandover[at]gmail[dot]com</b>. I don't really have much
                in the way of social media aside from{" "}
                <a
                    aria-label="Social media link"
                    href="https://www.linkedin.com/in/henrywandover/"
                    target="_blank"
                    rel="noreferrer noopener"
                    title="LinkedIn"
                >
                    LinkedIn
                </a>
                . There are more programming-related things on{" "}
                <a
                    aria-label="External GitHub link"
                    href="https://github.com/yung-turabian"
                    target="_blank"
                    rel="noreferrer noopener"
                    title="GitHub"
                >
                    GitHub
                </a>{" "}
                and{" "}
                <a
                    aria-label="External Codeberg link"
                    href="https://codeberg.org/yung-turabian"
                    target="_blank"
                    rel="noreferrer noopener"
                    title="GitHub"
                >
                    Codeberg
                </a>
                . For more artistic endeavours refer to my{" "}
                <a
                    aria-label="Social media link"
                    href="https://www.youtube.com/@yungturabian"
                    target="_blank"
                    rel="noreferrer noopener"
                    title="YouTube"
                >
                    YouTube
                </a>
                .
            </p>
            <ul>
                <li>
                    <a href="/links" title="Sites I Enjoy">
                        External sites of interest
                    </a>
                </li>
                <li>
                    <p>
                        <a href="/pgp.txt" title="text file">
                            My PGP pubkey
                        </a>
                    </p>
                </li>
            </ul>
        </div>
    );
}

// src/lib/modules/about.svelte
<script lang="ts">
	import resume from '$lib/docs/Resume.pdf';
</script>

<h2>About Me</h2>
<p>
	Hey there, welcome to my site! I'm Henry, a recent graduate of Bard College in the computer science program. 
	Currently residing in Philadelphia, I work on software projects related to programming languages 
	and desktop developer tools. Along with what I do in my free time, 
	I am also looking for work, ideally, either in backend software or game development. 
	If you have an opportunity, or know of one, feel free to check out my 
		<a href={resume} hreflang="en" target="_blank" rel="noreferrer noopener" type="application/pdf">résumé</a>, 
	as well as the rest of my site.
</p>
<p>
	The ideal way of getting in contact is by email: <b>henrywandover[at]gmail[dot]com</b>. I don't
	really have much in the way of social media aside from
	<a
		aria-label="Social media link"
		href="https://www.linkedin.com/in/henrywandover/"
		target="_blank"
		rel="noreferrer noopener"
		title="LinkedIn">LinkedIn</a
	>. There are more programming-related things on
	<a
		aria-label="External GitHub link"
		href="https://github.com/yung-turabian"
		target="_blank"
		rel="noreferrer noopener"
		title="GitHub">GitHub</a
	> and 
	<a
		aria-label="External Codeberg link"
		href="https://codeberg.org/yung-turabian"
		target="_blank"
		rel="noreferrer noopener"
		title="GitHub">Codeberg</a
	>.
	For more artistic endeavours refer to my 
	<a
		aria-label="Social media link"
		href="https://www.youtube.com/@yungturabian"
		target="_blank"
		rel="noreferrer noopener"
		title="YouTube">YouTube</a
	>.
</p>
<ul>
	<li><a href="/links" title="Sites I Enjoy">External sites of interest</a></li>
	<li><p><a href="/pgp.txt" title="text file">My PGP pubkey</a></p></li>
</ul>
